// 🎨 Color Themes for MovieView
// Use these hex colors to customize the player appearance

const COLOR_THEMES = {
    // Streaming Services
    'Netflix': 'e50914',      // Netflix Red
    'YouTube': 'ff0000',       // YouTube Red
    'Twitch': '9146ff',        // Twitch Purple
    'Discord': '5865f2',       // Discord Blue
    'Spotify': '1db954',       // Spotify Green
    'Amazon': 'ff9900',        // Amazon Orange
    'HBO': '000000',           // HBO Black
    'Hulu': '3ee000',          // Hulu Green
    
    // Brands
    'Apple': 'a2aaad',         // Apple Gray
    'Microsoft': '00a4ef',     // Microsoft Blue
    'Google': '4285f4',        // Google Blue
    'Meta': '0a66c2',          // Meta Blue
    
    // Primary Colors
    'Blue': '3b82f6',
    'Red': 'ef4444',
    'Green': '10b981',
    'Purple': '8b5cf6',
    'Pink': 'ec4899',
    'Orange': 'f97316',
    'Yellow': 'eab308',
    'Cyan': '06b6d4',
    
    // Dark Variants
    'Dark Blue': '1e40af',
    'Dark Red': '7f1d1d',
    'Dark Green': '064e3b',
    'Dark Purple': '3e1f47',
    'Dark Pink': '500724',
};

// 🔧 How to Use in script.js:
// Change this line in the playMovie() function:
/*
const playerUrl = `${VIDKING_BASE_URL}/movie/${tmdbId}?color=3b82f6&autoPlay=true`;
                                                            ^^^^^^^^
                                                      Replace with hex color
*/

// Example: Using Netflix Red
// const playerUrl = `${VIDKING_BASE_URL}/movie/${tmdbId}?color=e50914&autoPlay=true`;

// Example: Using Spotify Green
// const playerUrl = `${VIDKING_BASE_URL}/movie/${tmdbId}?color=1db954&autoPlay=true`;

// 🚀 Advanced Player Configuration
const PLAYER_CONFIG = {
    // Basic movie player
    movie: (tmdbId, color = '3b82f6') => {
        return `${VIDKING_BASE_URL}/movie/${tmdbId}?color=${color}&autoPlay=true`;
    },
    
    // Movie with start time (in seconds)
    movieWithProgress: (tmdbId, startTime = 0, color = '3b82f6') => {
        return `${VIDKING_BASE_URL}/movie/${tmdbId}?color=${color}&autoPlay=true&progress=${startTime}`;
    },
    
    // TV Series (requires season and episode)
    tvSeries: (tmdbId, season = 1, episode = 1, color = '3b82f6') => {
        return `${VIDKING_BASE_URL}/tv/${tmdbId}/${season}/${episode}?color=${color}&autoPlay=true`;
    },
    
    // Full featured TV (with all controls)
    tvFull: (tmdbId, season = 1, episode = 1, color = '3b82f6') => {
        return `${VIDKING_BASE_URL}/tv/${tmdbId}/${season}/${episode}?color=${color}&autoPlay=true&nextEpisode=true&episodeSelector=true`;
    },
};

// 📊 Player Features Available
const PLAYER_FEATURES = {
    'autoPlay': {
        description: 'Start playing automatically',
        default: true,
        example: '?autoPlay=true'
    },
    'color': {
        description: 'Primary player color (hex)',
        default: '3b82f6',
        example: '?color=e50914'
    },
    'nextEpisode': {
        description: 'Show next episode button (TV only)',
        default: false,
        example: '?nextEpisode=true'
    },
    'episodeSelector': {
        description: 'Enable episode selection menu (TV only)',
        default: false,
        example: '?episodeSelector=true'
    },
    'progress': {
        description: 'Start time in seconds',
        default: 0,
        example: '?progress=120'
    },
};

// 💡 Example URLs Generated by MovieView

const EXAMPLE_URLS = {
    'Netflix Style': 'https://www.vidking.net/embed/movie/1078605?color=e50914&autoPlay=true',
    'Spotify Style': 'https://www.vidking.net/embed/movie/1078605?color=1db954&autoPlay=true',
    'Purple Theme': 'https://www.vidking.net/embed/movie/1078605?color=8b5cf6&autoPlay=true',
    'With Progress': 'https://www.vidking.net/embed/movie/1078605?color=3b82f6&progress=600&autoPlay=true',
    'TV Show': 'https://www.vidking.net/embed/tv/119051/1/8?color=e50914&autoPlay=true&nextEpisode=true&episodeSelector=true',
};

// 🎯 Integration Examples
/*

// In HTML (simple embed)
<iframe src="https://www.vidking.net/embed/movie/1078605?color=e50914&autoPlay=true" 
        width="100%" 
        height="600" 
        frameborder="0" 
        allowfullscreen>
</iframe>

// In JavaScript (MovieView does this automatically)
function playMovie(tmdbId, title, overview, rating, year) {
    const playerUrl = `${VIDKING_BASE_URL}/movie/${tmdbId}?color=e50914&autoPlay=true`;
    document.getElementById('videoPlayer').src = playerUrl;
}

// With event tracking
window.addEventListener('message', function (event) {
    const data = JSON.parse(event.data);
    console.log('Player event:', data.event);
    console.log('Current time:', data.currentTime);
    console.log('Duration:', data.duration);
});

*/
