#!/bin/bash

# MovieView - Deploy to Vercel
# This script helps you deploy MovieView to Vercel in 3 steps

echo "🎬 MovieView - Vercel Deployment Guide"
echo "======================================="
echo ""

# Step 1
echo "Step 1: Initialize Git (if not already done)"
echo "-------------------------------------------"
echo "Run these commands:"
echo ""
echo "git init"
echo "git add ."
echo "git commit -m 'Initial MovieView commit'"
echo ""
echo "Then push to GitHub:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/movieview.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

# Step 2
echo "Step 2: Connect to Vercel"
echo "-------------------------"
echo "1. Go to https://vercel.com"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project'"
echo "4. Select your 'movieview' repository"
echo "5. Click 'Deploy'"
echo ""

# Step 3
echo "Step 3: Done! Your site is live!"
echo "--------------------------------"
echo "Your app will be available at: https://movieview-XXXX.vercel.app"
echo ""
echo "Every time you push to GitHub, Vercel will auto-deploy!"
echo ""

# Testing
echo "🧪 Local Testing"
echo "----------------"
echo "Before deploying, test locally:"
echo ""
echo "Option 1 (Python):"
echo "  python3 -m http.server 8000"
echo ""
echo "Option 2 (Node.js):"
echo "  npx http-server"
echo ""
echo "Then open: http://localhost:8000"
echo ""

# Features
echo "✨ Features Ready to Use"
echo "------------------------"
echo "✅ Trending movies from TMDB"
echo "✅ Real-time movie search"
echo "✅ Embedded Vidking player (50K+ movies)"
echo "✅ Watch progress tracking"
echo "✅ Fully responsive design"
echo "✅ Dark theme with custom colors"
echo "✅ Zero dependencies, zero build step"
echo "✅ Auto-deploy on push"
echo ""

# Files
echo "📁 Project Files"
echo "----------------"
echo ""
echo "📄 index.html          - Main page structure"
echo "🎨 style.css           - All styling & responsive design"
echo "⚙️  script.js           - All logic & API integration"
echo "📋 COLOR_THEMES.js     - Color customization reference"
echo "📖 README.md           - Full documentation"
echo "⚡ QUICKSTART.md       - Quick deployment guide"
echo "🎨 CUSTOMIZATION.md    - How to customize"
echo "⚙️  vercel.json         - Vercel configuration"
echo ".gitignore            - Git configuration"
echo ""

# Customization
echo "🎨 Customization Quick Tips"
echo "----------------------------"
echo ""
echo "Change player color (Netflix red):"
echo "  Edit script.js, line 43"
echo "  Change: color=3b82f6"
echo "  To:     color=e50914"
echo ""
echo "Change theme colors:"
echo "  Edit style.css, lines 8-16 (CSS variables)"
echo ""
echo "Change site title:"
echo "  Edit index.html, line 6"
echo ""

# Troubleshooting
echo "🐛 Troubleshooting"
echo "------------------"
echo ""
echo "Movies won't load?"
echo "  → Check internet connection"
echo "  → Refresh the page"
echo "  → Check browser console (F12)"
echo ""
echo "Player won't play?"
echo "  → Try a different movie"
echo "  → Reload the page"
echo "  → Check Vidking service status"
echo ""
echo "Deployment issues?"
echo "  → Check Vercel dashboard"
echo "  → Verify GitHub push succeeded"
echo "  → Check browser console"
echo ""

# Done
echo "🎉 You're all set!"
echo "===================="
echo ""
echo "Next steps:"
echo "1. Test locally with: python3 -m http.server 8000"
echo "2. Push to GitHub"
echo "3. Deploy via https://vercel.com"
echo ""
echo "Happy streaming! 🎬🍿"
